### PR TITLE
Run tests on Travis

### PR DESCRIPTION
**Pull request by edmorley**
This runs the tests on Travis under Python 2.7 and 3.4-3.6, since in later PRs I'd like to make a few small changes to wsgi-sslify - and running the tests on Travis seems like a sensible first step prior to that :-)

A requirements file has been added to simplify testing locally (along with README steps for running the tests), and a Travis badge will show the current state of upstream master.

For an example Travis test run, see the one that ran on my fork:
https://travis-ci.org/edmorley/wsgi-sslify/builds/110753710

Prior to merging this, Travis will need to be enabled for the upstream repo (which only the owner can do), by visiting this page and toggling the switch:
https://travis-ci.org/profile

For more details, see the individual commit messages.

### CODE REVIEW

**Comment by edmorley** [comment]
@jacobian, I don't suppose you've had a chance to look at this or the other open PR? :-)

**Comment by edmorley** [comment]
@jacobian could you take a look at this? (Or alternatively, are you open to accepting additional maintainers?)

Thanks :-)

**Comment by edmorley** [comment]
@jacobian, would you be open to me being an additional maintainer of this package? :-)

**Comment by jacobian** [comment]
@edmorley yes, thank you! I've added you as a collaborator, please go ahead.

**Comment by edmorley** [comment]
Many thanks! :-)

**Comment by edmorley** [comment]
> yes, thank you! I've added you as a collaborator, please go ahead.

@jacobian - sorry for the extremely delayed response! Thank you for adding as a collaborator - before I merge this PR it would help to have Travis activated for this repo, but this is something only the repo owner can do. I don't suppose you could do so here?
https://travis-ci.org/jacobian/wsgi-sslify

(Or if that link doesn't work, go via: https://travis-ci.org/profile)

Hopefully this should be the last I have to pester you :-)

**Comment by jacobian** [comment]
Should be done!

**Comment by edmorley** [comment]
Many thanks!

I've also added Python 3.6 to the mix, which was released since.

**Pull request merged**
